### ISSUE TITLE
Dynamically swapping the current subtitle track no longer works properly

### ISSUE THREAD

**Issue by stevenspmd** [videojs/video.js#3263]
## Description
Dynamically swapping the current subtitle track no longer works properly.

## Steps to reproduce
1. Create a videojs instance
2. Call addRemoteTextTrack
3. Call removeRemoteTextTrack and addRemoteTextTrack with a different subtitle file.

## Results
The displayed subtitles are not from the current text track

### Expected
The displayed subtitles should be from the current text track

### Actual
The displayed subtitles are not from the current text track

### Error output
None

## Additional Information
This works in 5.8.8 and breaks in the 5.9.2 pre-release.

#### videojs
5.9.2

#### browsers
Firefox, IE

#### OSes
Windows

### plugins
None

**Comment by gkatsev** [comment]
Can you please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.

When you add the new track, do you change it's mode? Also, is the video still playing or is it paused?

**Comment by stevenspmd** [comment]
https://jsfiddle.net/stevenspmd/tjf8agc6/ ; This fiddle is with the 5.8.8 release which works, it's the 5.9.0-2 which has problems. Unfortunately, the CDN does not seem to have 5.9.0-2 available.

**Comment by gkatsev** [comment]
5.9.0-2 was an alpha release for testing the audio tracks work. If it works in the main releases like 5.8.8 and new brand new 5.9.0 stable release then it sounds like it could possibly be an issue with that PR.
I'll make a note of that there but otherwise, seems like this isn't an issue.

**Comment by stevenspmd** [comment]
Never said it worked with 5.9.0, in fact it fails .. swap the version of video.js, use IE and the wrong subtitle track is displayed.

**Comment by gkatsev** [comment]
Ah, ok, I misunderstood. I'll re-open while we try and figure out the issue.

**Comment by gkatsev** [comment]
Ah, ok, so, I think I understand what's going on. You're trying to remove tracks based on the return value from `addRemoteTextTrack`. There's a bug about it (https://github.com/videojs/video.js/issues/2046) which is getting fixed in today's patch release soon (https://github.com/videojs/video.js/pull/3253).

Related to it, if there are multiple text tracks enabled in our emulated text track implementation (this does happen to be Firefox and most versions of IE) then we'll display the first track available. I just wrote about this as part of the new tracks documentaiton (https://github.com/videojs/video.js/pull/3256/commits/33a7bca01a56b8c91277507165809671361354e4)

Also, why are you having a drop-down replace the tracks available in the player? It would be much better to include all the tracks as children of the video element, then you can populate your drop down based on the values in `player.textTracks()`, and then you can turn on and off tracks you want or not want by setting their mode to `showing`. (https://github.com/gkatsev/video.js/blob/text-tracks-docs/docs/guides/tracks.md#interacting-with-text-tracks).

Hope that helps.

**Comment by stevenspmd** [comment]
Basically we have an existing ui which is flash based (which we are trying to get ride of slowly) and we don't want change the look and feel of the ui controls. Basically a user can not tell if they are using flash or html5 video for the player. As for dynamically swapping subtitle tracks, its just plain easier to only have one subtitle track given our code setup at the moment.

**Comment by gkatsev** [comment]
You don't have to use the controls but rather just the API. It should make it a lot easier to just have to do `selectecTrack.mode = 'showing'` rather than removing and adding tracks, plus it will save networks requests since it won't need to try and download the tracks each time.

**Comment by stevenspmd** [comment]
Possibly but doubt that will doesn't fix the underlying problem we are experiencing.

**Comment by gkatsev** [comment]
It will because you wouldn't be tripping into the bug that you're experiencing (#2046).
Anyway, I'm closing this issue because I'm fairly certain that it's a duplicate of #2046 which is getting fixed really soon by #3253.
If that happens to not be the case, we can always re-open this issue later.
