### ISSUE TITLE
Issue with async play() in Chrome

### ISSUE THREAD

**Issue by diestrin** [videojs/video.js#3474]
## Description
Chrome recently changed the play() method to return a promise, and this is causing issue when you call load() or pause() before the promise is resolved:
_Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()_
_Uncaught (in promise) DOMException: The play() request was interrupted by a call to load()_

## Steps to reproduce
1. Use Chrome
2. Go to http://videojs.com/advanced/ and open the web console
3. Play the video and click in the timeline in a place where the video isn't buffered yet (try using a network throttling if the video is loading too fast)
4. Move the timeline again to a place where the video isn't buffered yet (The issue will start after the second time you do this)

-- or --

1. Go to http://videojs.com/advanced/ and open the web console
2. Play any video
3. Quickly play another video before the 1st start to reproduce
4. You can do step 3 as many times as you want quickly and you'll see a lot of errors in the console

## Results
En error is logged, but the video is still working
### Expected
Wait for the play() promise to be resolved before calling another method
### Actual
The play is expected to be sync and thus pause() and load() are being callede inmediatelly
### Error output
Case 1: _Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()_
Case 2: _Uncaught (in promise) DOMException: The play() request was interrupted by a call to load()_

## Additional Information
Bug report in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=593273
#### videojs
5.10.7 and 5.11.0
#### browsers
Chrome 51.0.2704.103 (not only this version)
#### OSes
OSx 10.10.5 (not only this OS)
### plugins
No

**Comment by wingchuihk** [comment]
Thank you Austin for the call this morning, and got a better understanding
on the product. I m looking forward to hear back from your team.

Have a great weekend!
Kenneth

**Comment by gkatsev** [comment]
This will be fixed by https://github.com/videojs/video.js/pull/3518

**Comment by misteroneill** [comment]
This should be fixed in 5.11.3

**Comment by antonioribeiro** [comment]
I'm doing

    videojs.seek(seekTo).pause();

And receiving this

![image](https://cloud.githubusercontent.com/assets/3182864/20503984/54969d6c-b02c-11e6-949d-41fff926bc1d.png)

On 

    * Video.js 5.13.2 <http://videojs.com/>

Removing the pause fixes warning, but, of course, video start playing. Is this something I'm doing wrong?

**Comment by beaufortfrancois** [comment]
For info, I've just published an article about this exact issue at https://developers.google.com/web/updates/2017/06/play-request-was-interrupted that tells you exactly what is happening and **how to fix it**.

**Comment by thijstriemstra** [comment]
Just ran into this issue with 6.2.0, thanks for the article @beaufortfrancois.

**Comment by shikkaba** [comment]
Still seeing this in 6.2.4. Is it still happening in 6.2.8?

**Comment by benweidig** [comment]
Still seeing this in 6.4.0 if I seek a second time while player is still loading video for the first seek.
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
Promise (async)
Html5.(anonymous function) @ video.js:19703
techGet_ @ video.js:21423
play @ video.js:21465
handleMouseUp @ video.js:13946
bound @ video.js:2232
data.dispatcher @ video.js:1867
```

**Comment by gkatsev** [comment]
Unless you're seeing issues with playback, you can safely ignore this error.

**Comment by GeyseR** [comment]
I was able to reproduce the issue on videojs.com site. This is how it looks when user has relatively slow internet connection speed: [play-pause-bug-on-videojs-com.zip](https://github.com/videojs/video.js/files/1671529/play-pause-bug-on-videojs-com.zip)
Hope this helps.

**Comment by H1D** [comment]
version `7.0.0-alpha.1` the issue is still here

**Comment by gkatsev** [comment]
@chuchuva Can you please provide more information about where you're seeing the issue and detailed steps to reproduce?

**Comment by chuchuva** [comment]
@gkatsev I saw it in the logs. I can't reproduce it, sorry. 😞
