### ISSUE TITLE
playbackRate Menu Item not appearing on Mobile

### ISSUE THREAD

**Issue by WaluTechnician** [videojs/video.js#4398]
## Description
I'm using Video JS to play videos on my site and I'm trying to use the playbackRate option, but it only works on desktop, I can't seem to get it to work on my android chrome.

walukungfu.org/test.html

I left a couple sources to work with, I get the issue with either one. 

## Steps to reproduce
                <script src="js/jquery-3.1.1.min.js"></script>
		<script src="http://vjs.zencdn.net/5.19.2/video.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.5.3/videojs-contrib-hls.min.js"></script>
		<script src="js/responsiveslides.js"></script>
                <video id="test" class="video-js vjs-default-skin vjs-16-9" data-setup='{ "playbackRates": [0.5, 1, 2, 4] }' poster="images/indexvidposter.png" controls>
				<source src="images/indexvid.mp4" type="video/mp4"/>
				<source src="images/indexvid/playlist.m3u8" type="application/x-mpegURL"/>
				
                                </video>
				<script>
                               var player = videojs('test');
                              </script>
## Results

No playbackRate button on menu in Android Chrome

### Expected
To have a playback rate button on the controls in mobile as well as desktop

### Actual
Only getting the playback rate button on Desktop

### Error output
No errors on standard Page view. I'm still too novice to debug myself...

## Additional Information
Video JS 5.19
Chrome for Android
VJS-HLS-contrib included, but it's use has no bearing on the issue.

Thank you for any help you can provide.

**Comment by gkatsev** [comment]
Chrome for Android for a long time didn't support playback rate changes and so, we were hiding it with user agent detection because it also lied via feature detection saying that it existed. In [video.js 5.20.0](https://github.com/videojs/video.js/pull/4336), we removed that restriction and things should be working now.

Hope that helps.

**Comment by WaluTechnician** [comment]
Thank you for your prompt response, @gkatsev 

I changed from loading v5.19 via CDN to loading v6.2.0 from the js file on my server. I'm still getting the same issue unfortunately. Should I use v5.20? 

I've changed my test page to reflect this:

walukungfu.org/test.html

Thank you for being so attentive to the people who use your plugin. 

Video.js has allowed my Kung Fu School to post videos of our classes to our own website instead of dealing with the hassle of Youtube's Fair Use appeal system for the fact that we leave Pandora Radio on while we train.

If you're ever in south Florida come check us out, you'll be more than welcome.

**Comment by gkatsev** [comment]
Hm... it seems to be working on my device. What version of Chrome for Android are you running this on? Also, thanks for mentioning the test page again, totally missed it in my first read-through.

--------------

Also, thanks! it means a lot to hear that.
I actually used to do kung fu back in the bay.

**Comment by WaluTechnician** [comment]
I was running Chrome v 55.

I updated to v58 and the button appears on mobile and functions properly when using an MP4 source.

When using a segmented video source (M3U8 [HLS]) on mobile the option appears but doesn't change the play rate when a different one is selected, but I think that's something for the fellas who made vjs-contrib-hls.

It does work with M3U8 on desktop though 0.o

If you want to see that situation you can have a look here:

walukungfu.org/test2.html

Thanks again for all you've done here.

**Comment by mister-ben** [comment]
Unless you have `videojs.options.hls.overrideNative = true` contrib-hls won't be used on Android Chrome since it has native support for HLS.

If Chrome has fixed playbackRate with particular formats only that's annoying. MP4 works.

**Comment by mister-ben** [comment]
Confirmed that Chrome's native HLS still does not support playbackRate. HLS with contrib-hls and overrideNative works.

**Comment by gkatsev** [comment]
Yeah, seems like it only works in some cases. JWplayer just disabled it for HLS: https://github.com/jwplayer/jwplayer/pull/2107
