### ISSUE TITLE
dispose() gives error: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by DimaM-BeStreet** [videojs/video.js#5706]
## Description
Hey guys, I've been going crazy for a full day over this bug, thinking i must be missing something (i still might be)
basically I get an error every time I use dispose, including this super simple reduced case:
https://codepen.io/dimam-bestreet/pen/GPmoxX

## Steps to reproduce
1. add dynamically a video
2. run .dispose on it
3. look in the chrome (Chromium 65) dev-tools for this error:
VM76237:214 Uncaught TypeError: Cannot read property 'classList' of null
    at VideojsDelegate (<anonymous>:214:46)
    at add_element (<anonymous>:395:17)
    at MutationObserver.<anonymous> (<anonymous>:419:17)

### Expected
no error..

### Actual
error... ^^

### Error output
If there are any errors at all, please include them here.
VM76237:214 Uncaught TypeError: Cannot read property 'classList' of null
    at VideojsDelegate (<anonymous>:214:46)
    at add_element (<anonymous>:395:17)
    at MutationObserver.<anonymous> (<anonymous>:419:17)

## Additional Information
I've checked in firefox - no error!
I am using crome (Chromium 65) on linux (if that has anything to do with anything)

#### videojs
7.3.0
#### browsers
Chromium 65, firefox seems ok
#### OSes
I've checked only mine - linux mint 17.3
### plugins
nope

Is this is only related to the fact im using Chromium 65??

**Comment by gkatsev** [comment]
Unfortunately, I'm unable to reproduce locally or in browserstack on chrome 65 on win10 or macos.

**Comment by DimaM-BeStreet** [comment]
I'll test it on my phone this week, if it works - no problem really...
Thank you!
Dima

**Comment by thijstriemstra** [comment]
I think i've seen this in a unit test before (so don't wait for `ready` event but `dispose` right away or something like that).

**Comment by armaha** [comment]
Hi,
I also notice the same issue, with almost the exact same stack trace for VideoJs 6.6. It also only occurs in Chrome. We block our instance from calling dispose if not ready like this: 
```
if(this.player) {
    this.player.dispose();
}

```
We instantiate the player like this:
```
const nonReadyPlayer = videojs(
                    this.videoId,
                    this.videoConfig,
                    () => {
                        this.player = nonReadyPlayer;
                    }
);
```

As we cannot reproduce this exception, it is difficult to pinpoint why this is occurring in a very small number of instances ( n<0.01% of requests). I also cannot find any references to VideoJsDelegate MutationObserver  in VideoJs release 6.6.  

Is there any specific behavior for autoplay that needs to be guarded against in chrome?
Where does VideoJSDelegate come from if not from video.js repo?

Thanks!

**Comment by travisbader** [comment]
I think i found a good stack trace.  I will attach as our bug tracking too reports it as it is easy to read as formatted.

![Screen Shot 2020-06-08 at 8 27 52 AM](https://user-images.githubusercontent.com/7252621/84049990-fd035f80-a961-11ea-8892-0aba3441d61f.png)

**Comment by thijstriemstra** [comment]
@gkatsev can this be re-opened? A check for `element` seems to be needed in `dom.js`:

```javascript
if (element && element.classList) {
```

**Comment by gkatsev** [comment]
I'm not seeing an error locally.
While I'm not necessarily opposed to adding a null check to that method but almost always there's something else that needs to be fixed in cases like this.

**Comment by gkatsev** [comment]
Anyone have info on how to reproduce this issue?

**Comment by travisbader** [comment]
@gkatsev See above, there are steps to reproduce in the initial description.  It appears to be related to disposing and re-creating video-js objects within a component

**Comment by gkatsev** [comment]
As I mentioned above, I'm unable to reproduce with either the test page or locally.

**Comment by thijstriemstra** [comment]
> As I mentioned above, I'm unable to reproduce with either the test page or locally.

I wasn't able to reproduce it with that test page either, but while playing with it, I was able to break it using:

```javascript
      videojs("my_video", {}, function ready() {
        console.log("ready");
        videojs("my_video").dispose();
      });
```

I don't think it should throw this/any error:

![Screenshot from 2020-08-27 19-05-26](https://user-images.githubusercontent.com/305679/91472851-55c70200-e898-11ea-89f0-99e18091d2cd.png)

**Comment by gkatsev** [comment]
Looks like a different error but related to disposing. It probably should handle that case gracefully. Probably a timing issue with `preselectTrack` there.

**Comment by thijstriemstra** [comment]
I agree. Wouldn't surprise me that fixing this issue reveals the other issue..

**Comment by damjan25** [comment]
@gkatsev 
Is there a plan to release this in 7.10.1 ? https://github.com/videojs/video.js/pull/6701/files 
Would be really nice. I am seeing this error a lot lately. 

(Using videojs + videojsima plugin)
This error gets thrown when I get `AdsLoader error: AdError 303: No Ads VAST response after one or more Wrappers`
And after player tries to dispose, this error(**Cannot read property 'classList' of null**) gets thrown.
But for some reason only when I **hard reload** the page.

**Comment by gkatsev** [comment]
We just merged #6967, hopefully that should fix some of the issues related to this.

**Comment by thijstriemstra** [comment]
#6701 was merged and I think this can be closed.

**Comment by gkatsev** [comment]
Thanks for following up. Forgot to close it as part of the commit.

**Comment by gkatsev** [comment]
Fix is in 7.14.2.

**Comment by arifuxd** [comment]
> Fix is in 7.14.2.

No This is not fixed. I am currently getting it in 7.15.4

![image](https://user-images.githubusercontent.com/79258272/139529522-19b57e4f-1f2f-465d-a4fb-04e12c538c4e.png)

**Comment by damjan25** [comment]
Still have this error :/

**Comment by mister-ben** [comment]
The issue demonstrated in the test case was fixed when this was closed. If you are seeing an issue in a different scenario, please open a new issue with steps to reproduce.
